// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/components/base/Card.vue')['default']
    BaseContainer: typeof import('./src/components/base/Container.vue')['default']
    SettingDarkModeSwitch: typeof import('./src/components/setting/DarkModeSwitch.vue')['default']
    SettingFullscreen: typeof import('./src/components/setting/Fullscreen.vue')['default']
  }
}

export { }
